###
### SN127: tackler
### https://github.com/sn127/tackler
###

language: scala

jdk: oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

###
### Actual build definition
###

script:
   - sbt clean coverage test

after_success:
   # coverageAggregate must be on separate step by sbt-coveralls
   # because this is multiproject build
   ### SBT 1.0 / sbt-coveralls
   ### - sbt coverageAggregate coveralls
   - sbt coverageReport
   - sbt coverageAggregate

